code refactor - separate activation of `imaging_report`
tdincer/element-calcium-imaging pull request #3
Opened 2022-10-19 17:37 UTC by ttngu207

2022-10-19 17:54 UTC, tdincer commented on element_calcium_imaging/plotting/cell_plot.py
> +    return masks
```suggestion
def paint_rois(image, mask_xpix, mask_ypix):
    SATURATION = 40
    VALUE = 255

    # Assign colors to each region
    masks = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)
    for xpix, ypix in zip(mask_xpix, mask_ypix):
        masks[ypix, xpix] = [np.random.random()*255, SATURATION, VALUE]
    return np.uint8(cv2.cvtColor(masks.astype(np.float32), cv2.COLOR_HSV2RGB))

```

2022-10-19 17:54 UTC, tdincer commented on element_calcium_imaging/plotting/cell_plot.py
> +    return masks
This will incorporate Dimitri's suggestion.

2022-10-19 17:58 UTC, tdincer commented on element_calcium_imaging/plotting/widget.py
> +    fig2_layout = get_tracelayout(None, width=FIG2_WIDTH, height=FIG2_HEIGHT)
```suggestion
    fig2_layout = cell_plot.get_tracelayout(None, width=FIG2_WIDTH, height=FIG2_HEIGHT)

```

2022-10-19 17:59 UTC, tdincer commented on element_calcium_imaging/plotting/widget.py
> +                    # & f"activity_type='z_score'"
```suggestion
```

2022-10-19 17:59 UTC, tdincer commented on element_calcium_imaging/plotting/widget.py
> +            background_image = single_to_3channel_image(image, low_q=0, high_q=99.9)
```suggestion
            background_image = cell_plot.single_to_3channel_image(image, low_q=0, high_q=99.9)

```

2022-10-19 18:00 UTC, tdincer commented on element_calcium_imaging/plotting/widget.py
> +            background_image_with_cells_painted = paint_rois(
```suggestion
            background_image_with_cells_painted = cell_plot.paint_rois(

```

2022-10-19 18:12 UTC, tdincer commented
cell_plot needs access to imaging module. This seems to be the kind of chicken-egg problem that is not allowed in python I believe (a.k.a. circular import problem). Am I missing something?

2022-10-20 11:46 UTC, ttngu207 commented
> `cell_plot` needs access to an `imaging` module. This seems to be the kind of chicken-egg problem that is not allowed in python I believe (a.k.a. circular import problem). Am I missing something?

`cell_plot` does not need to import `imaging`. The 2 functions `plot_cell_overlayed_image` and `plot_cell_traces` indeed need `imaging`, but it's passed in as input argument. This is to avoid that chicken-egg problem, the idea is, by the time those 2 functions are to be called, the caller would already have `imaging` defined and can pass in as input argument.
Obviously this is not very elegant, would have been nice if `cell_plot` can know about the activated `imaging` module and just import it, but I haven't figured out yet how to best achieve that.

2022-10-21 14:14 UTC, tdincer commented
> > `cell_plot` needs access to an `imaging` module. This seems to be the kind of chicken-egg problem that is not allowed in python I believe (a.k.a. circular import problem). Am I missing something?
> 
> `cell_plot` does not need to import `imaging`. The 2 functions `plot_cell_overlayed_image` and `plot_cell_traces` indeed need `imaging`, but it's passed in as input argument. This is to avoid that chicken-egg problem, the idea is, by the time those 2 functions are to be called, the caller would already have `imaging` defined and can pass in as input argument. Obviously this is not very elegant, would have been nice if `cell_plot` can know about the activated `imaging` module and just import it, but I haven't figured out yet how to best achieve that.

Right there is no problem. It took me sometime to follow the imports. I think we are good with this.

2022-10-21 14:19 UTC, tdincer requested changes

2022-10-21 14:19 UTC, tdincer commented on element_calcium_imaging/plotting/widget.py
> +            cells_maskid_image = make_maskid_image(
```suggestion
            cells_maskid_image = cell_plot.make_maskid_image(

```

2022-10-21 14:19 UTC, tdincer commented on element_calcium_imaging/plotting/widget.py
> +            background_with_cells = alpha_combine_2images(
```suggestion
            background_with_cells = cell_plot.alpha_combine_2images(

```

2022-10-21 14:19 UTC, tdincer commented on element_calcium_imaging/imaging_report.py
>  import plotly.graph_objects as go
```suggestion
```

2022-10-21 14:19 UTC, tdincer commented on element_calcium_imaging/plotting/cell_plot.py
> +    ).fetch("mask", "mask_xpix", "mask_ypix")
These queries are problematic. This function does not have access to the `imaging` module. We also cannot import any of the `imaging` modules because it'll be a circular import.

2022-10-21 14:19 UTC, tdincer commented on element_calcium_imaging/plotting/widget.py
> +            cells_maskid_image = make_maskid_image(
`make_maskid_image` needs the `cell_plot`.

2022-10-21 14:29 UTC, tdincer commented on element_calcium_imaging/plotting/cell_plot.py
> +    ).fetch("mask", "mask_xpix", "mask_ypix")
I was wrong. I see how it works now.

2022-10-21 14:32 UTC, tdincer approved these changes

2022-10-21 14:32 UTC, merged